version: '3.10'
services:

  app:
    container_name: app
    build: ./app
    command: python manage.py runserver
    volumes:
      - ./app/:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev

  db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      postgres_data:

    enviroment:
      - POSTGRESS_PASSWORD=123
      - POSTGRESS_DB=rentabycicle_db
      - POSTGRESS_USER=rentabycicle_user
    restart:
      always

  nginx:
  container_name: nginx
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./config.conf:/etc/nginx/conf.d

