version: '3.10'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    enviroment:
      POSTGRESS_PASSWORD: 123
      POSTGRESS_DB: rentabycicle_db
      PGDATA: /var/lib/postgresql/data/pgdata
    restart:
      always
