# Generated by Django 3.2.8 on 2021-10-25 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BycicleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45, verbose_name='Company name')),
            ],
        ),
        migrations.CreateModel(
            name='Bycicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bycicle_compamy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bycicle.byciclecompany')),
            ],
        ),
    ]
